# Generated by Django 2.2 on 2019-06-11 06:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название экскурсии', max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('time_begin', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(help_text='Менеджер группы туристов', max_length=200)),
                ('status', models.CharField(blank=True, choices=[('r', 'сформирована'), ('e', 'на экскурсии')], default='r', help_text='Статус групп туристов', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название отеля', max_length=300)),
                ('addres', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('cost_for_one_day', models.DecimalField(decimal_places=2, max_digits=7)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный номер каждого туриста', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_arrival', models.DateField()),
                ('date_of_departure', models.DateField()),
                ('docs', models.FileField(upload_to='')),
                ('note', models.TextField(help_text='Примечание', max_length=1000)),
                ('status', models.CharField(blank=True, choices=[('r', 'заявка сформирована'), ('c', 'оплачено'), ('d', 'пакет документов готов'), ('h', 'заселен в отель'), ('e', 'на экскурсии')], default='r', help_text='Статус туриста', max_length=1)),
                ('excursion', models.ManyToManyField(help_text='Выберите экскурсии для туриста', to='tourists.Excursion')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourists.Group')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourists.Hotel')),
            ],
        ),
    ]
